### ISSUE TITLE
Lepton pt thresholds

### ISSUE THREAD

**Issue by EmyrClement** [BristolTopGroup/NTupleProduction#139]
At the moment, the pt threshold on the signal lepton is 30 GeV : [electron filter] (https://github.com/BristolTopGroup/NTupleProduction/blob/CMSSW_7_3_X/python/TopPairElectronPlusJetsSelectionFilter_cfi.py) [muon filter] (https://github.com/BristolTopGroup/NTupleProduction/blob/CMSSW_7_3_X/python/TopPairMuonPlusJetsSelectionFilter_cfi.py)

However the current triggers (in PHYS14 samples) are :

HLT_Ele32_eta2p1_WP85_Gsf
and
HLT_IsoMu24_eta2p1_IterTrk02

At the moment, the offline electron pt threshold is too low and the muon pt threshold is possibly too high.  I don't think there's much we can do at the moment, but we should make sure these make sense when the trigger menu is finalised.  I'll increase the offline pt threshold in the electron channel to 32 for now.

**Comment by kreczko** [comment]
The p<sub>T</sub> threshold is something we will set once we know which trigger to use. At the moment, since we have MC only, this is not crucial.

For muons the cut should be around 26 GeV (as previous reference selection).

Also, could you please remind me of the <sub>T</sub> threshold of the H<sub>T</sub> trigger?
