### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by DouglasBurns** [BristolTopGroup/NTupleProduction#289]
When we submit dataset=all to DICE we create a snapshot of ntp be be tarred for each dataset. This seems a bit wasteful and time intensive

**Comment by kreczko** [comment]
This should already be the case:
https://github.com/BristolTopGroup/NTupleProduction/blob/master/python/ntp/commands/run/__init__.py#L71

So why is it not working?

Well, it seems that we create a new object for every dataset:
https://github.com/BristolTopGroup/NTupleProduction/blob/master/python/ntp/commands/run/ntuple/__init__.py#L153
which means that `self.__have_fresh_tar_files` is lost.

So there are two possible solutions since the Task feature is not yet implemented (spoilers :)):
 - change `self.__have_fresh_tar_files` to be a class variable (`Command.__have_fresh_tar_files`)
 - define a better way to say 'I have a fresh tar file'

The latter is a bit more complex, since you would like frequent changes for testing.
I think I will implement the former which is a lot faster.
